-- MySQL Script generated by MySQL Workbench
-- 2020-04-24T08:52:31 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`aircraft_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`aircraft_type` (
  `idAircraftType` INT NOT NULL AUTO_INCREMENT,
  `a/c` VARCHAR(3) NULL,
  `size` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idAircraftType`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`airport` (
  `idAirport` INT(11) NOT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `country` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`idAirport`),
  UNIQUE INDEX `idAirport_UNIQUE` (`idAirport` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`Ruter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Ruter` (
  `(A)rrival/(D)eparture` VARCHAR(1) NULL,
  `route_nr` VARCHAR(10) NULL,
  `origin/destination` VARCHAR(3) NULL,
  `idRoutes` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idRoutes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Flights` (
  `date` DATE NULL DEFAULT NULL,
  `STA/STD` TIME NULL DEFAULT NULL,
  `idRoutes` INT NULL,
  `Ruter_idRoutes` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Ruter_idRoutes`),
  CONSTRAINT `fk_Flights_1`
    FOREIGN KEY (`Ruter_idRoutes`)
    REFERENCES `airport`.`Ruter` (`idRoutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`booth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`booth` (
  `idBooth` INT(11) NOT NULL AUTO_INCREMENT,
  `booth_type` VARCHAR(10) NULL DEFAULT NULL,
  `available` TINYINT(4) NULL DEFAULT NULL,
  `Flights_idFlights` INT(11) NULL,
  PRIMARY KEY (`idBooth`),
  INDEX `fk_Booth_Flights1_idx` (`Flights_idFlights` ASC) VISIBLE,
  CONSTRAINT `fk_Booth_Flights1`
    FOREIGN KEY (`Flights_idFlights`)
    REFERENCES `airport`.`Flights` (`Ruter_idRoutes`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`terminals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`terminals` (
  `idTerminals` INT(11) NOT NULL AUTO_INCREMENT,
  `airline` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idTerminals`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`terminals_has_booth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`terminals_has_booth` (
  `Terminals_idTerminals` INT(11) NOT NULL AUTO_INCREMENT,
  `Booth_idBooth` INT(11) NOT NULL,
  PRIMARY KEY (`Terminals_idTerminals`, `Booth_idBooth`),
  INDEX `fk_Terminals_has_Booth_Booth1_idx` (`Booth_idBooth` ASC) VISIBLE,
  INDEX `fk_Terminals_has_Booth_Terminals1_idx` (`Terminals_idTerminals` ASC) VISIBLE,
  CONSTRAINT `fk_Terminals_has_Booth_Booth1`
    FOREIGN KEY (`Booth_idBooth`)
    REFERENCES `airport`.`booth` (`idBooth`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Terminals_has_Booth_Terminals1`
    FOREIGN KEY (`Terminals_idTerminals`)
    REFERENCES `airport`.`terminals` (`idTerminals`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `airport`.`Fly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Fly` (
  `idFLy` INT NOT NULL,
  `A/C` VARCHAR(3) NOT NULL,
  `idAircraftType` INT NULL,
  `Flights_idFlights` INT(11) NULL,
  `idBooth` INT(11) NULL,
  PRIMARY KEY (`idFLy`),
  INDEX `fk_Fly_1_idx` (`Flights_idFlights` ASC) VISIBLE,
  INDEX `fk_Fly_3_idx` (`idAircraftType` ASC) VISIBLE,
  INDEX `fk_Fly_2_idx` (`idBooth` ASC) VISIBLE,
  CONSTRAINT `fk_Fly_1`
    FOREIGN KEY (`Flights_idFlights`)
    REFERENCES `airport`.`Flights` (`Ruter_idRoutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fly_2`
    FOREIGN KEY (`idBooth`)
    REFERENCES `airport`.`booth` (`idBooth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fly_3`
    FOREIGN KEY (`idAircraftType`)
    REFERENCES `airport`.`aircraft_type` (`idAircraftType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Arrival_Actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Arrival_Actions` (
  `idArrival_Actions` INT NOT NULL AUTO_INCREMENT,
  `Flights_idFlights` INT(11) NULL,
  `Taxi_ind` DATETIME NULL,
  `Passagerer_ud` DATETIME NULL,
  `Bagage_ud` DATETIME NULL,
  PRIMARY KEY (`idArrival_Actions`),
  INDEX `fk_Arrival_Actions_1_idx` (`Flights_idFlights` ASC) VISIBLE,
  CONSTRAINT `fk_Arrival_Actions_1`
    FOREIGN KEY (`Flights_idFlights`)
    REFERENCES `airport`.`Flights` (`Ruter_idRoutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Departure Actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Departure Actions` (
  `idDeparture Actions` INT NOT NULL AUTO_INCREMENT,
  `Flights_idFlights` INT(11) NULL,
  `Braendstof_paafyldning` DATETIME NULL,
  `Rengoering_varepaafyldning` DATETIME NULL,
  `Bagage_ind` DATETIME NULL,
  `Passagerer_ind` DATETIME NULL,
  `Taxi_ud` DATETIME NULL,
  PRIMARY KEY (`idDeparture Actions`),
  INDEX `fk_Departure Actions_1_idx` (`Flights_idFlights` ASC) VISIBLE,
  CONSTRAINT `fk_Departure Actions_1`
    FOREIGN KEY (`Flights_idFlights`)
    REFERENCES `airport`.`Flights` (`Ruter_idRoutes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Mangler:\n\nTaxi til ventepladser\nPersonaletil/fra naboplads\nPersonale til/fra øvrige i egen terminal\nPersonale til/fra den anden terminal\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
